# Generated by Django 5.2.6 on 2025-09-07 16:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('car_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('caravan', 'Caravan'), ('van', 'Van'), ('truck', 'Truck')], default='car', max_length=12)),
                ('engine_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('seats', models.PositiveIntegerField(blank=True, null=True)),
                ('unlimited_seats', models.BooleanField(default=False)),
                ('available_pickup_locations', models.ManyToManyField(blank=True, related_name='pickup_vehicles', to='inventory.location')),
                ('available_return_locations', models.ManyToManyField(blank=True, related_name='return_vehicles', to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('awaiting pickup', 'Awaiting pickup'), ('awaiting drop off', 'Awaiting drop off'), ('rejected', 'Rejected')], default='reserved', max_length=20)),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_reservations', to='inventory.location')),
                ('return_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_reservations', to='inventory.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.vehicle')),
            ],
        ),
    ]
